apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: greeapyml-python 
  janus-idp.io/tekton: greeapyml-python
  backstage.io/kubernetes-id: greeapyml-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: greeapyml-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  